### ISSUE TITLE
Assassin 5-HP suicide on Shrub crashes Program

### ISSUE THREAD

**Issue by x0tek** [ShiraYuuki/TAO_REVIVED#12]
Assassin freezes game with the suicide attack - the attack can only be initiated at the condition where the assassin is sub-5HP, which triggers a "second attack option" by clicking on the center square of the assassin.

This attack can only be used when there is only ONE assassin - it does not work with more than one. 

This attack does maximum damage (99, armor irrelevant) to all units it attacks regardless of blocking (not going through barriers, it is "blocked" by them). It DOES kill un-barriered wards (Lightning Wards and otherwise).

**Comment by Jordanhho** [comment]
Solved!
