### ISSUE TITLE
Dragonspeaker Power Pull Miscalculation

### ISSUE THREAD

**Issue by x0tek** [ShiraYuuki/TAO_REVIVED#14]
The DragonSpeaker Mage (DSM) originally has the following logic:

"For each Pyromancer (Pyro) or DSM on the field, subtract 12 attack from all friendly Dragon Tyrants. Distribute this combined attack value equally among all Pyros and DSMs."

The issue is that the Dragon Tyrant in the game can lose attack value passed its 28 attack value, moving it into the negatives.

**Comment by Jordanhho** [comment]
Solved!!!
