### ISSUE TITLE
Initial-Turn Phase Problems

### ISSUE THREAD

**Issue by x0tek** [ShiraYuuki/TAO_REVIVED#15]
When the "turn phase" is selected initially, and a unit is chosen, the "direction" window does not pop until a unit has entered at least one of the other phases.

For example, if I want my turn to consist solely of turning my Enchantress to face the opposite direction without moving, I must first click on "move", then on the "turn" feature, rather than directly on the "turn" feature.

**Comment by Jordanhho** [comment]
solved
