### ISSUE TITLE
DSM Power-Reset "Undo" error

### ISSUE THREAD

**Issue by x0tek** [ShiraYuuki/TAO_REVIVED#27]
The DragonSpeaker Mage (DSM) resets its power to 15 in spite of a Dragon being present after clicking the "undo" button.

This was replicated in 3 different scenarios, and did not cause the game to crash when loaded from a save file.

**Comment by x0tek** [comment]
This error persists when "adding variation" as well.

**Comment by Jordanhho** [comment]
solved!
